# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f509e34aa8abd6b7e0fc18efbdbedb77e4ffa9a6f8b614f197e84e64eab1ede3533494686ef0267a7ee58450901785ced9b7ae82e1476ed485f32c4fc2c70b2

test:
  secret_key_base: ea8ce6622f7a31ad02238f37e29372222857ba534cb6ef2b8b098b688541749d7e2046c80268da2ac49c04d074e35dcfcb929e612cfc4422ca37514398781abe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
